### ISSUE TITLE
Add a Readme File

### ISSUE THREAD

**Issue by RahulSharma4329** [RahulSharma4329/Bandhu-Card-Landing-Page#2]

**Comment by Ghat0tkach** [comment]
hey , im willing to work on this issue .
i shall update readme by :
1)providing a brief description of website 
2) adding the contributer's list

**Comment by RahulSharma4329** [comment]
Surely you can. Assigning this to you.

**Comment by RahulSharma4329** [comment]
So this project is basically a landing page for a credit card company like Slice or Unicard. So write a description like that
