### ISSUE TITLE
Add Scroll to Top Button

### ISSUE THREAD

**Issue by SattyamSamania** [RahulSharma4329/Bandhu-Card-Landing-Page#3]
I would like to add Scroll to Top Button to add more interactivity for the users and we do not have to scroll back again and again. I can create  Scroll Button using HTML, CSS and JS. If you think that would be valuable feature kindly assign this issue to me. Thank You!

**Comment by RahulSharma4329** [comment]
I have assigned the Issue to you. Please create a new branch and contribute.

**Comment by SattyamSamania** [comment]
@RahulSharma4329 Why it's showing react-scripts' is not recognized as an internal or external command, after i run npm start?

**Comment by RahulSharma4329** [comment]
Do a npm install

**Comment by SattyamSamania** [comment]
> Do a npm install

@RahulSharma4329 Its opening on local host but nothing is showing. I can see the title only.

**Comment by RahulSharma4329** [comment]
The home page url is bugyy 

Try to go to 

localhost:3000/

it will open 

ill am fixing this issue asap

**Comment by RahulSharma4329** [comment]
i have fixed the issue do a git pull and everything should work fine

**Comment by himanshu1221** [comment]
If the issue is not resolved can you please assign this to me ?

**Comment by RahulSharma4329** [comment]
Let's give @SattyamSamania a little more time to solve the issue. If it would not be resolved even after a couple of days I'll ask him and assign it to you @himanshu1221

**Comment by SattyamSamania** [comment]
> Let's give @SattyamSamania a little more time to solve the issue. If it would not be resolved even after a couple of days I'll ask him and assign it to you @himanshu1221 

I think I made the PR. It has to be reviewed by you first.
